add README.md
PaulMartsiniv/taxi-service pull request #3
Opened 2021-12-14 15:56 UTC by PaulMartsiniv

2021-12-14 16:08 UTC, TankevychO requested changes

2021-12-14 16:08 UTC, TankevychO commented on README.md
> +####Using this app you can:
```suggestion
### This web app designed to simulate simple taxi service app.
#### Using this app you can:
```

2021-12-14 16:08 UTC, TankevychO commented on README.md
> +######For example
```suggestion
###### For example
```

2021-12-14 16:24 UTC, TankevychO approved these changes

2021-12-15 08:55 UTC, Nick97-git requested changes
- README.md -> Rewrite places that you took from examples, you know which ones, some of them could be deleted). Also, add url to the deployed project on heroku if you have one to the end of file
- Remove redundant `/` from endpoints like /cars/, /drivers/ and /manufacturers/ from all places where you use them
- ConnectionUtil ->  remove example of filled values and left uncommented part and uncomment it

2021-12-15 12:46 UTC, Nick97-git requested changes

2021-12-15 12:46 UTC, Nick97-git commented on src/main/java/taxi/util/ConnectionUtil.java
>      private static final String JDBC_DRIVER = "com.mysql.cj.jdbc.Driver";
add stubs for values like YOUR_URL and so on

2021-12-15 12:46 UTC, Nick97-git commented on system.properties
> +java.runtime.version=11
add empty line

2021-12-15 12:46 UTC, Nick97-git commented on README.md
> +![car_diagram_db_2_4f50942103](src/main/resources/image/shema_image.png)
remove this image, it's very popular)

2021-12-15 12:46 UTC, Nick97-git commented on README.md
> +* Maven Checkstyle Plugin
remove this line

2021-12-15 12:46 UTC, Nick97-git commented on README.md
> +- ApacheTomcat [TOMCAT](https://tomcat.apache.org/download-90.cgi)
```suggestion
- ApacheTomcat [Tomcat](https://tomcat.apache.org/download-90.cgi)
```

2021-12-15 13:36 UTC, Nick97-git requested changes

2021-12-15 13:36 UTC, Nick97-git commented on README.md
> +* Maven Checkstyle Plugin
you didn't remove this line

2021-12-15 13:36 UTC, Nick97-git commented on src/main/java/taxi/controller/car/GetMyCurrentCarsController.java
> +@WebServlet("/cars/profile/all")
```suggestion
@WebServlet("/drivers/cars")
```

2021-12-15 14:08 UTC, Nick97-git requested changes

2021-12-15 14:08 UTC, Nick97-git commented on src/main/java/taxi/controller/car/GetMyCurrentCarsController.java
> +@WebServlet("/cars")
you have the same URL for another page

2021-12-15 14:39 UTC, Nick97-git approved these changes

2021-12-15 14:45 UTC, merged